<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>New Job Application</title>
</head>
<body style="font-family: Arial;">

    <h2>📩 New Job Application Submitted</h2>

    <p>A new job application has been submitted. Details below:</p>

    <h3>👤 Applicant Information</h3>
    <p><strong>Name:</strong> {{ $data['name'] }}</p>
    <p><strong>Email:</strong> {{ $data['email'] }}</p>
    <p><strong>Phone:</strong> {{ $data['phone'] }}</p>
    <p><strong>Address:</strong> {{ $data['address'] ?? 'N/A' }}</p>

    <h3>💼 Professional Details</h3>
    <p><strong>Current Position:</strong> {{ $data['current_position'] ?? 'N/A' }}</p>
    <p><strong>Current Employer:</strong> {{ $data['current_employer'] ?? 'N/A' }}</p>

    <h3>📎 Uploaded Documents</h3>
    <ul>
        @if(!empty($data['cv']))
            <li>CV Uploaded</li>
        @endif
        @if(!empty($data['nrc']))
            <li>NRC Uploaded</li>
        @endif
        @if(!empty($data['grade12']))
            <li>Grade 12 Certificate Uploaded</li>
        @endif
        @if(!empty($data['degree']))
            <li>Degree Uploaded</li>
        @endif
        @if(!empty($data['masters']))
            <li>Masters Uploaded</li>
        @endif
        @if(!empty($data['other_documents']))
            <li>Other Documents Uploaded</li>
        @endif
    </ul>

    <p style="font-size:12px; color:gray;">
        This email was automatically generated by AAIB System.
    </p>

</body>
</html>